<?php
// Theme setup
function my_custom_theme_setup() {
    // Add support for featured images
    add_theme_support('post-thumbnails');

    // Add support for dynamic title tags
    add_theme_support('title-tag');

    // Add support for custom logos
    add_theme_support('custom-logo');

    // Register navigation menus
    register_nav_menus(array(
        'primary' => __('Primary Menu', 'my-custom-theme'),
        'footer' => __('Footer Menu', 'my-custom-theme'),
    ));
}
add_action('after_setup_theme', 'my_custom_theme_setup');

// Enqueue scripts and styles
function my_custom_theme_enqueue_scripts() {
    // Enqueue the main stylesheet
    wp_enqueue_style('my-theme-styles', get_stylesheet_directory_uri() . '/style.css');

    // Enqueue additional styles (like those generated by Next.js)
    wp_enqueue_style('nextjs-css', get_stylesheet_directory_uri() . '/.next/static/css/styles.css', array(), null, 'all');

    // Enqueue Next.js main JS file
    wp_enqueue_script('nextjs-main', get_stylesheet_directory_uri() . '/.next/static/chunks/main-app-18b335ae5e0000c5.js', array(), null, true);

    // Enqueue other Next.js generated JS files, if necessary
    // Example for another script file:
    // wp_enqueue_script('nextjs-another-script', get_stylesheet_directory_uri() . '/.next/static/chunks/another-script.js', array(), null, true);
}
add_action('wp_enqueue_scripts', 'my_custom_theme_enqueue_scripts');

// Disable the admin bar for all users
add_filter('show_admin_bar', '__return_false');

// Register widget areas
function my_custom_theme_widgets_init() {
    register_sidebar(array(
        'name' => __('Sidebar', 'my-custom-theme'),
        'id' => 'sidebar-1',
        'description' => __('Widgets in this area will be shown on all posts and pages.', 'my-custom-theme'),
        'before_widget' => '<section id="%1$s" class="widget %2$s">',
        'after_widget' => '</section>',
        'before_title' => '<h2 class="widget-title">',
        'after_title' => '</h2>',
    ));
}
add_action('widgets_init', 'my_custom_theme_widgets_init');

// Add theme support for custom backgrounds
add_theme_support('custom-background');

// Example of adding a custom post type
function my_custom_post_type() {
    register_post_type('product', array(
        'labels' => array(
            'name' => __('Products', 'my-custom-theme'),
            'singular_name' => __('Product', 'my-custom-theme'),
        ),
        'public' => true,
        'has_archive' => true,
        'rewrite' => array('slug' => 'products'),
        'supports' => array('title', 'editor', 'thumbnail', 'excerpt', 'comments'),
    ));
}
add_action('init', 'my_custom_post_type');

?>
